checks:
    php:
        code_rating: true
        duplication: true
filter:
    paths: ["src/*"]
    excluded_paths:
        - vendor/*
tools:
    php_code_sniffer:
        config:
            standard: Drupal,DrupalPractice
