sudo: required

services:
  - docker
  - docker-compose

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.17.1

before_install:
  - docker-compose up -d
  - docker ps

install:
  - docker-compose exec -u root php composer install

before_script:
  - docker-compose exec -u root php ./vendor/bin/run drupal:site-setup
  - docker-compose exec -u root php ./vendor/bin/run drupal:site-install --existing-config
  - docker-compose exec -u root php chown -R www-data:www-data build

script:
  - docker-compose exec -u root php ./vendor/bin/grumphp run
  - docker-compose exec -u root php ./vendor/bin/phpunit
  - docker-compose exec -u root php ./vendor/bin/behat

notifications:
  email: false
