language: php
dist: precise

php:
  - 7.0

env:
  global:
    - PATH=$PATH:/home/travis/.composer/vendor/bin:$TRAVIS_BUILD_DIR/vendor/bin
  matrix:
    - DRUPAL_VERSION=8.3.x-dev
    - DRUPAL_VERSION=8.4.x-dev
    - DRUPAL_VERSION=8.5.x-dev

matrix:
  allow_failures:
    - php: 7.0
      env: DRUPAL_VERSION=8.5.x-dev

install:
  - composer self-update
  - composer install

before_script:
  # Start PhantomJS server.
  - phantomjs --webdriver=4444 > /dev/null &
  # Set sendmail so drush doesn't throw an error during site install.
  - echo "sendmail_path='true'" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`
  # Create database.
  - mysql -e 'create database drupal'
  # Install Drupal 8 target site.
  - cd tests/cores/drupal8
  - composer require drupal/core:$DRUPAL_VERSION --dev --prefer-dist
  - cd drupal
  - ../vendor/bin/drush si config_installer -y --db-url=mysql://travis:@127.0.0.1/drupal config_installer_sync_configure_form.sync_directory=../config/sync
  # Run Drush web server.
  - ../vendor/bin/drush --debug runserver :8888 > ~/debug.txt 2>&1 &
  - sleep 4s
  - chmod -R ug+w sites
  - cd ../../../..

script:
  - grumphp run
  - phpunit
  - behat --strict -c tests/cores/drupal8/behat.yml.dist

notifications:
  email: false
